const ACTION_LABELS = {
  'create': 'יצירה',
  'update': 'עדכון',
  'delete': 'מחיקה',
  'assign': 'שיוך',
  'assign_pm': 'שיוך מנהל פרויקט',
  'status_change': 'שינוי סטטוס',
  'reopen': 'פתיחה מחדש',
  'upload': 'העלאה',
  'register': 'הרשמה',
  'contractor_proof_uploaded': 'הוכחת תיקון הועלתה',
  'proof_deleted': 'הוכחה נמחקה',
  'manager_approved_closed': 'אושר וסגור ע"י מנהל',
  'manager_rejected_returned': 'נדחה והוחזר ע"י מנהל',
  'admin_phone_change': 'שינוי טלפון (אדמין)',
  'admin_change_phone': 'שינוי טלפון (אדמין)',
  'self_phone_change': 'שינוי טלפון (עצמי)',
  'phone_changed': 'מספר טלפון שונה',
  'admin_change_role': 'שינוי תפקיד (אדמין)',
  'role_change': 'שינוי תפקיד',
  'session_revoked': 'ביטול סשן',
  'admin_access': 'גישת אדמין',
  'expired': 'פג תוקף',
  'accepted': 'התקבל',
  'created': 'נוצר',
  'resend': 'שליחה מחדש',
  'cancelled': 'בוטל',
  'auto_linked': 'שויך אוטומטית',
  'bulk_create_floors': 'יצירת קומות',
  'bulk_create_units': 'יצירת יחידות',
  'insert_floor': 'הוספת קומה',
  'resequence': 'סידור מחדש',
  'project_discipline_add': 'הוספת תחום',
  'project_plan_delete': 'מחיקת תוכנית',
  'excel_import': 'ייבוא מאקסל',
  'migrate_sort_index': 'עדכון סדר מיון',
  'extend_trial': 'הארכת ניסיון',
  'comp': 'מתנה עד תאריך',
  'suspend': 'חסימה',
  'unsuspend': 'ביטול חסימה',
  'billing_override': 'שינוי חיוב',
  'billing_suspend': 'חסימה',
  'billing_unsuspend': 'ביטול חסימה',
  'billing_extend_trial': 'הארכת ניסיון',
  'billing_comp': 'מתנה עד תאריך',
  'phone_change_admin': 'שינוי טלפון (אדמין)',
  'project_billing_updated': 'עדכון חיוב פרויקט',
  'contracted_units_changed': 'שינוי יחידות חוזיות',
  'billing_handoff_requested': 'בקשת העברה לחיוב',
  'billing_handoff_acknowledged': 'אישור קבלת בקשה',
  'project_billing_setup_completed': 'השלמת הגדרת חיוב',
  'org_role_changed': 'שינוי תפקיד בארגון',
  'member_removed_from_org': 'הסרת חבר מהארגון',
  'member_removed_from_project': 'הסרת חבר מפרויקט',
  'role_changed': 'שינוי תפקיד',
  'invoice_generated': 'הפקת חשבונית',
  'invoice_marked_paid': 'סימון חשבונית כשולם',
};

const ENTITY_LABELS = {
  'task': 'ליקוי',
  'task_update': 'עדכון ליקוי',
  'task_attachment': 'קובץ מצורף',
  'subscription': 'מנוי',
  'user': 'משתמש',
  'project': 'פרויקט',
  'building': 'בניין',
  'floor': 'קומה',
  'unit': 'יחידה',
  'company': 'חברה',
  'project_company': 'חברת פרויקט',
  'project_plan': 'תוכנית פרויקט',
  'unit_plan': 'תוכנית יחידה',
  'project_discipline': 'תחום פרויקט',
  'project_trade': 'מקצוע פרויקט',
  'invite': 'הזמנה',
  'invoice': 'חשבונית',
};

const NOTIF_EVENT_LABELS = {
  'task_assigned': 'שיוך משימה',
  'status_waiting_verify': 'ממתין לאימות',
  'status_closed': 'סגירה',
  'manual_send': 'שליחה ידנית',
  'contractor_proof_uploaded': 'הוכחת קבלן',
  'manager_approved': 'אישור מנהל',
  'manager_rejected': 'דחייה',
  'media_followup': 'המשך מדיה',
  'invite_created': 'הזמנה נוצרה',
};

export const getActionLabel = (action) => ACTION_LABELS[action] || '—';
export const getEntityLabel = (entityType) => ENTITY_LABELS[entityType] || '—';
export const getNotifEventLabel = (eventType) => NOTIF_EVENT_LABELS[eventType] || '—';
export { ACTION_LABELS, ENTITY_LABELS, NOTIF_EVENT_LABELS };
